name: dchat
description: Command line AI chat application
version: 0.0.1
repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

dependencies:
  args: ^2.4.2
  console: ^4.1.0
  quiver: ^3.2.1
  meta: ^1.10.0
  http: ^1.1.0
  maybe_just_nothing: ^0.5.3
  dart_openai: ^4.0.0
  toml: ^0.14.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
  build_runner: ^2.4.6
  build_test: ^2.2.1
  json_to_model: ^3.2.4
